---

  - name: Install Apache packages (Ubuntu)
    apt:
      name:
        - apache2

  - name: Change email address for admin
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: "^ServerAdmin"
      line: Serveradmin serveradmin@serv.com
    register: apache2

  - name: Restart apache service
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: Change default Apache web page
    copy:
      src: /home/ubuntu/ansible-demo/guide/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'

  - name: Start apache service (Ubuntu)
    service:
      name: apache2
      state: started
      enabled: yes
