---

- include_tasks: prepare_hosts.yml


- include_tasks: configure_db.yml
  when: "'db-servers' in group_names"

- include_tasks: configure_apache.yml
  when: "'web-servers' in group_names"

- include_tasks: configure_samba.yml
  when: "'file-servers' in group_names"


